//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRLog.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuoteLog
    {
        public Nullable<System.DateTime> BidDate { get; set; }
        public string BiddingAs { get; set; }
        public string BidTo { get; set; }
        public string ProjectName { get; set; }
        public Nullable<short> LastAddendumRecvd { get; set; }
        public string Estimator { get; set; }
        public Nullable<int> QuoteNumber { get; set; }
        public Nullable<int> UID { get; set; }
        public string Notes { get; set; }
        public string EngineersEstimate { get; set; }
        public string Division { get; set; }
        public string RedSheet { get; set; }
        public string ScopeLetter { get; set; }
        public Nullable<bool> BidTypeIandC { get; set; }
        public Nullable<bool> BidTypeElectrical { get; set; }
        public Nullable<bool> BidTypeNOBID { get; set; }
        public Nullable<bool> MandetoryJobWalk { get; set; }
        public Nullable<System.DateTime> JobWalkDate { get; set; }
        public Nullable<System.DateTime> QADeadLineDateTime { get; set; }
        public string QuoteStatus { get; set; }
        public Nullable<System.DateTime> dtpLastDateFollowup { get; set; }
        public string LastFollowupBy { get; set; }
        public string FollowupNote { get; set; }
        public string EmailAddress { get; set; }
        public int Id { get; set; }
    }
}
