//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_config
    {
        public int Id { get; set; }
        public string FlagName { get; set; }
        public string Value { get; set; }
    }
}
