//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttachmentsForBidLog
    {
        public int UID { get; set; }
        public int RowId { get; set; }
        public byte[] ListOfAttachments { get; set; }
        public string FileNames { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
