//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBID_Checklist
    {
        public Nullable<int> SRNumber { get; set; }
        public Nullable<bool> PrequalificationRequired { get; set; }
        public Nullable<bool> IsTelstarPrequalified { get; set; }
        public Nullable<bool> QualificationPacketReceived { get; set; }
        public Nullable<bool> Map { get; set; }
        public Nullable<bool> BidForm { get; set; }
        public Nullable<bool> SubsRequireListing { get; set; }
        public Nullable<bool> EquipmentRequiresListing { get; set; }
        public Nullable<bool> SpareParts { get; set; }
        public string IsAnotherContractorHardSpecdForThisWork { get; set; }
        public string EquipmentRequiresListingText { get; set; }
        public string SparePartsText { get; set; }
        public string ElectricalEngineer { get; set; }
        public string ElectricalEngineeringContact { get; set; }
        public string CustomerContact { get; set; }
        public string PAndSSourcePh { get; set; }
        public string Weblink { get; set; }
        public string PlanholdersList { get; set; }
        public string HowLongDoWeNeedToHoldPricesFor { get; set; }
        public string BidScheduleItemsTelstarIsBiddingOn { get; set; }
        public string Instrumentation { get; set; }
        public string PlcControls { get; set; }
        public string Hmi { get; set; }
        public string Power { get; set; }
        public string PlcProgrammingBy { get; set; }
        public string HmiProgrammingBy { get; set; }
        public string ReportProgrammingBy { get; set; }
        public string WhoAreYouGoingToUseForTheIntegration { get; set; }
        public string WasThereAPrequalProcess { get; set; }
        public string QualificationsProcess { get; set; }
        public string WhenWillYouNotifyUsThatWeWillBeListed { get; set; }
        public string HaveThereBeenAnyAddendumsListedSoFar { get; set; }
        public string AreYouTheOneThatDecidesTheSystemsIntegrator { get; set; }
        public string WhenIsTheNextPrequalification { get; set; }
        public int BIDChecklist_Id { get; set; }
    }
}
