//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustContact
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string CustomerContact { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<bool> IsPrimaryContact { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
