//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRLog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public string User_Password { get; set; }
        public bool SR_Log_ReadOnly { get; set; }
        public string User_Name { get; set; }
        public bool Admin_Rights { get; set; }
        public bool Bid_Log_ReadOnly { get; set; }
        public Nullable<bool> Accounting_Rights { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> DatabaseUpdate_Rights { get; set; }
    }
}
